apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webtest
  name: webtest
  namespace: test
  annotations:
    fluxcd.io/automated: "true"
    #fluxcd.io/tag.webtest: regex:^3.10.*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webtest
  strategy: 
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webtest
    spec:
      containers:
      - image: sebidude/webtest
        name: webtest
        resources: {}
        env:
          - name: LISTEN_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: webtest
                key: listenAddress
status: {}
